mod 'elastic-kibana', '6.3.1'
mod 'elastic-elastic_stack', '6.3.2'
mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-apt', '7.7.1'
mod 'puppetlabs-translate', '2.2.0'
mod 'puppet-yum', '4.3.0'
mod 'puppetlabs-concat', '6.4.0'
mod 'puppetlabs-yumrepo_core', '1.0.7'
mod 'elastic-elasticsearch', '6.4.0'
mod 'richardc-datacat', '0.6.2'
mod 'elastic-logstash', '6.1.5'
mod 'puppet-archive', '4.6.0'
mod 'puppetlabs-java', '6.5.0'
mod 'tc-elk',
  :git => 'https://github.com/tcinden/tc-elk.git'